CREATE TABLE PREDMET ( 

        SIFRA VARCHAR2(10) PRIMARY KEY, 

        NAZIV VARCHAR2(100) NOT NULL, 

        SEMESTAR INTEGER, 

        KATEDRA VARCHAR2(50) 

); 

  

CREATE TABLE STUDENT ( 

        BR_INDEKSA VARCHAR2(10) PRIMARY KEY, 

        LIME VARCHAR2(50) NOT NULL, 

        IME_RODITELJA VARCHAR2(50), 

        PREZIME VARCHAR2(50) NOT NULL, 

        SMER VARCHAR2(50) 

); 

  

CREATE TABLE IZVESTAJ ( 

        ID INTEGER PRIMARY KEY, 

        OPIS VARCHAR2(500) NOT NULL, 

        DATUM_PREDAJE DATE 

); 

  

CREATE TABLE PRED_NAST ( 

        S_PREDMETA VARCHAR2(10), 

        IME_NASTAVNIKA VARCHAR2(50) NOT NULL, 

        CONSTRAINT  PRED_NAST_PK PRIMARY KEY(S_PREDMETA , IME_NASTAVNIKA), 

        CONSTRAINT  PREDMET_FK FOREIGN KEY(S_PREDMETA) REFERENCES PREDMET(SIFRA) ON DELETE CASCADE 

); 

 
CREATE TABLE PROJEKAT ( 

    ID INTEGER PRIMARY KEY, 

    TIP_PROJEKTA VARCHAR2(15) NOT NULL, 

    NAZIV VARCHAR2(100) NOT NULL, 

    SKOLSKA_GODINA_ZADAVANJA VARCHAR2(9) NOT NULL, 

    S_PREDMETA VARCHAR2(10), 

    FOREIGN KEY (S_PREDMETA) REFERENCES predmet(SIFRA), 

    CONSTRAINT CHK_TIP_PROJEKTA CHECK (TIP_PROJEKTA IN ('grupni', 'pojedinacni'))  

); 

 

CREATE TABLE TEORIJSKI_PROJEKAT ( 

    ID INTEGER PRIMARY KEY, 

    MAKS_BROJ_STRANA INTEGER, 

    FOREIGN KEY (ID) REFERENCES PROJEKAT(ID) 

); 

  

CREATE TABLE PRAKTICNI_PROJEKAT ( 

    ID INTEGER PRIMARY KEY, 

    KRATAK_OPIS VARCHAR2(200), 

    PREPORUCENI_PROGRAMSKI_JEZIK VARCHAR2(50), 

    FOREIGN KEY (ID) REFERENCES PROJEKAT(ID) 

); 

 

CREATE TABLE PPROJ_PREP_WEB ( 

    PPROJ_ID INTEGER, 

    PREP_WEB_STRANA VARCHAR2(255) NOT NULL, 

    PRIMARY KEY(PPROJ_ID, PREP_WEB_STRANA), 

    FOREIGN KEY(PPROJ_ID) REFERENCES PRAKTICNI_PROJEKAT(ID) ON DELETE CASCADE 

); 

 

CREATE TABLE LITERATURA ( 

    LIT_ID VARCHAR2(10) PRIMARY KEY, 

    NAZIV VARCHAR2(100) NOT NULL 

); 

 

CREATE TABLE LIT_AUTOR ( 

    LIT_ID VARCHAR2(10), 

    AUTOR VARCHAR2(100) NOT NULL, 

    PRIMARY KEY (LIT_ID, AUTOR), 

    FOREIGN KEY (LIT_ID) REFERENCES LITERATURA(LIT_ID) 

); 

 

CREATE TABLE KNJIGA ( 

    ISBN VARCHAR2(20) PRIMARY KEY, 

    IZDAVAC VARCHAR2(100), 

    GODINA_IZDANJA INTEGER, 

    LIT_ID VARCHAR2(10), 

    FOREIGN KEY (LIT_ID) REFERENCES LITERATURA(LIT_ID) 

); 

 

CREATE TABLE CLANAK_U_CASOPISU ( 

    ISSN VARCHAR2(20) PRIMARY KEY, 

    IME_CASOPISA VARCHAR2(100) NOT NULL, 

    BROJ INTEGER, 

    GODINA INTEGER, 

    LIT_ID VARCHAR2(10), 

    FOREIGN KEY (LIT_ID) REFERENCES LITERATURA(LIT_ID) 

); 

 

CREATE TABLE RAD ( 

    ID VARCHAR2(20) PRIMARY KEY, 

    URL VARCHAR2(255), 

    KONFERENCIJA_OBJAVLJIVANJA VARCHAR2(100), 

    FORMAT VARCHAR2(20), 

    LIT_ID VARCHAR2(10), 

    FOREIGN KEY (LIT_ID) REFERENCES LITERATURA(LIT_ID), 

    CONSTRAINT CHK_FORMAT CHECK (FORMAT IN ('word', 'post-script', 'pdf')) 

); 

 

CREATE TABLE SADRZI ( 

    TPROJ_ID INTEGER, 

    LIT_ID VARCHAR2(10), 

    PRIMARY KEY (TPROJ_ID, LIT_ID), 

    FOREIGN KEY (TPROJ_ID) REFERENCES TEORIJSKI_PROJEKAT(ID), 

    FOREIGN KEY (LIT_ID) REFERENCES LITERATURA(LIT_ID) 

); 

 

 

CREATE TABLE PREDAO ( 

    IZVESTAJ_ID INTEGER, 

    STUDENT_ID VARCHAR2(10), 

    PROJEKAT_ID INTEGER, 

    BROJ_IZVESTAJA INTEGER, 

    FOREIGN KEY (IZVESTAJ_ID) REFERENCES IZVESTAJ(ID), 

    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(BR_INDEKSA), 

    FOREIGN KEY (PROJEKAT_ID) REFERENCES PROJEKAT(ID), 

    PRIMARY KEY (IZVESTAJ_ID, STUDENT_ID, PROJEKAT_ID) 

); 

 

CREATE TABLE UCESTVUJE ( 

    PROJEKAT_ID INTEGER, 

    STUDENT_ID VARCHAR2(10), 

    DATUM_POCETKA_IZRADE DATE NOT NULL, 

    DATUM_ZAVRSETKA DATE, 

    ROK_ZA_ZAVRSETAK DATE NOT NULL, 

    PROJEKAT_ZAVRSEN VARCHAR2(2), 

    ODABRAN_PROG_JEZIK VARCHAR2(50), 

    URL_DOKUMENTACIJE_PROG_JEZIKA VARCHAR2(255), 

    DOPUNSKA_LITERATURA VARCHAR2(300), 

    CHECK (PROJEKAT_ZAVRSEN IN ('da', 'ne')), 

    PRIMARY KEY (PROJEKAT_ID, STUDENT_ID), 

    FOREIGN KEY (PROJEKAT_ID) REFERENCES PROJEKAT (ID), 

    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT (BR_INDEKSA) 

); 