@WebAPI_HostAddress = https://localhost:5276

POST https://localhost:5276/Projekat/Prakticni/Izvestaj/Dodaj/21/18021
Content-Type: application/json

{
  "Opis": "Opis izvestaja",
  "DatumPredaje": "2024-05-30T12:00:00"
}

###s obzirom da se dinamicki postavlja id izvestaja, postaviti odgovarajuci id za azuriranje

PUT https://localhost:5276/Projekat/Prakticni/Izvestaj/Azuriraj
Content-Type: application/json
{
  "Id": 93,
  "Opis": "Azurirani opis izvestaja",
  "DatumPredaje": "2025-05-30T12:00:00"
}

###s obzirom da se dinamicki postavlja id izvestaja, postaviti odgovarajuci id za brisanje

DELETE https://localhost:5276/Projekat/Prakticni/Izvestaj/Obrisi/93

###s obzirom da se dinamicki postavlja id izvestaja, postaviti odgovarajuci id za preuzimanje

GET https://localhost:5276/Projekat/Prakticni/Izvestaj/Preuzmi/93

###

GET https://localhost:5276/Projekat/Prakticni/Izvestaj/PreuzmiZaStudenta/21/18021
