@WebAPI_HostAddress = https://localhost:5276


GET {{WebAPI_HostAddress}}/Projekat/Prakticni/Preuzmi/ZaPredmet/CS102

###
POST {{WebAPI_HostAddress}}/Projekat/Prakticni/Dodaj
Content-Type: application/json
{
    "projekat": {
        "Naziv": "NazivProjekta",
        "SkolskaGodinaZadavanja": "2024/2025",
        "PreporuceniProgramskiJezik": "C#",
        "VrstaProjekta": "prakticni",
        "TipProjekta": "grupni",
        "KratakOpis": "Kratak opis projekta",
        "PripadaPredmetu": {
            "Id": "CS102"
        }
    },
    "stranice": [
        {
            "Naziv": "WebStranica1"
        },
        {
            "Naziv": "WebStranica2"
        }
    ]
}

###

GET {{WebAPI_HostAddress}}/Projekat/Prakticni/VratiProjekat/254

### s obzirom da se dinamicki postavlja id projekta, postaviti odgovarajuci id za azuriranje

PUT {{WebAPI_HostAddress}}/Projekat/Prakticni/Azuriraj
Content-Type: application/json

{
    "projekat": {
        "Id": 254,
        "Naziv": "NazivProjekta1",
        "SkolskaGodinaZadavanja": "2024/2026",
        "PreporuceniProgramskiJezik": "C++",
        "VrstaProjekta": "prakticni",
        "TipProjekta": "grupni",
        "KratakOpis": "Kratak opis projekta1",
        "PripadaPredmetu": {
            "Id": "CS102"
        }
    },
    "stranice": [
        {
            "Naziv": "WebStranica1"
        },
        {
            "Naziv": "WebStranica2"
        }
    ]
}
### s obzirom da se dinamicki postavlja id projekta, postaviti odgovarajuci id za brisanje

DELETE {{WebAPI_HostAddress}}/Projekat/Prakticni/Obrisi/254

### Za testiranje funkcije ispod dodata su dva ucesca
POST {{WebAPI_HostAddress}}/Ucesce/Dodaj/254/18033
Content-Type: application/json

{
  "DatumPocetkaIzrade": "2022-10-01T00:00:00",
  "RokZaZavrsetak": "2022-12-20T00:00:00",
  "OdabranProgramskiJezik":"C#",
  "UrlDokumentacijeProgJezika":"https://learn.microsoft.com/en-us/dotnet/csharp/"
}

###

POST {{WebAPI_HostAddress}}/Ucesce/Dodaj/254/18032
Content-Type: application/json

{
  "DatumPocetkaIzrade": "2022-10-01T00:00:00",
  "RokZaZavrsetak": "2022-12-20T00:00:00",
  "OdabranProgramskiJezik":"C#",
  "UrlDokumentacijeProgJezika":"https://learn.microsoft.com/en-us/dotnet/csharp/"
}

###

GET {{WebAPI_HostAddress}}/Projekat/Teorijski/Preuzmi/Studenti/51

###s obzirom da se dinamicki postavlja id projekta, postaviti odgovarajuci id za brisanje ucesnika

DELETE {{WebAPI_HostAddress}}/Projekat/Prakticni/ObrisiSvaUcesca/254




