@WebAPI_HostAddress =  https://localhost:5276

GET {{WebAPI_HostAddress}}/Predmet/Preuzmi/Sve

###

GET {{WebAPI_HostAddress}}/Predmet/Preuzmi/Sortirani?katedra=Rač&semestar=3

###

POST {{WebAPI_HostAddress}}/Predmet/Dodaj
Content-Type: application/json

{
  "Id": "MAT101",
  "Naziv": "Matematika1",
  "Semestar": 1,
  "Katedra": "Matematika"
}

###

PUT {{WebAPI_HostAddress}}/Predmet/Izmeni
Content-Type: application/json

{
  "Id": "MAT101",
  "Naziv": "Matematika 1",
  "Semestar": 1,
  "Katedra": "Matematika"
}

###

DELETE {{WebAPI_HostAddress}}/Predmet/Obrisi/MAT101

###

GET {{WebAPI_HostAddress}}/Predmet/Preuzmi/MAT101

###