@WebAPI_HostAddress = https://localhost:5276

GET {{WebAPI_HostAddress}}/Projekat/Prakticni/PreporuceneWebStranice/Preuzmi/28

###

POST {{WebAPI_HostAddress}}/Projekat/Prakticni/PreporuceneWebStranice/Dodaj/28
Content-Type: application/json

{
  "naziv": "VasNaziv"
}

###



DELETE {{WebAPI_HostAddress}}/Projekat/Prakticni/PreporuceneWebStranice/Obrisi/28
Content-Type: application/json

{
  "naziv": "VasNaziv"
}
###
