@WebAPI_HostAddress = https://localhost:5276

GET {{WebAPI_HostAddress}}/projekat/PreuzmiProjekteZaPredmet/CS102

###

GET {{WebAPI_HostAddress}}/projekat/PreuzmiSortiraneProjekteZaPredmet/CS108?vrsta=prakticni&tip=grupni&godina=2023/2024

###
