@WebAPI_HostAddress = https://localhost:5276


GET {{WebAPI_HostAddress}}/Student/PreuzmiStudente

###

GET {{WebAPI_HostAddress}}/Student/PreuzmiSortiraneStudente?brIndeksa=1802&ime=M

###

POST {{WebAPI_HostAddress}}/Student/DodajStudenta
Content-Type: application/json

{
  "brIndeksa": "19001",
  "lIme": "Marko",
  "imeRoditelja": "Ilija",
  "prezime": "Ivanovic",
  "smer": "Racunarstvo"
}

###

DELETE {{WebAPI_HostAddress}}/Student/ObrisiStudenta/19001

###

PUT {{WebAPI_HostAddress}}/Student/IzmeniStudenta
Content-Type: application/json

{
  "brIndeksa": "19001",
  "lIme": "Nenad",
  "imeRoditelja": "Ilija",
  "prezime": "Ivanovic",
  "smer": "Racunarstvo"
}

###

GET {{WebAPI_HostAddress}}/student/PreuzmiStudenta/19001

###
