@WebAPI_HostAddress = https://localhost:5276


# Dobavljanje svih studenata
GET {{WebAPI_HostAddress}}/Student/PreuzmiStudente
###

# Dobavljanje sortiranih studenata sa opcionalnim filterima
GET {{WebAPI_HostAddress}}/Student/PreuzmiSortiraneStudente?brIndeksa=1802&ime=M
###

# Dodavanje novog studenta
POST {{WebAPI_HostAddress}}/Student/DodajStudenta
Content-Type: application/json

{
  "brIndeksa": "19001",
  "lIme": "Marko",
  "imeRoditelja": "Ilija",
  "prezime": "Ivanovic",
  "smer": "Racunarstvo"
}
###

# Brisanje studenta sa određenim brojem indeksa
DELETE {{WebAPI_HostAddress}}/Student/ObrisiStudenta/19001
###

# Izmena podataka o studentu
PUT {{WebAPI_HostAddress}}/Student/IzmeniStudenta
Content-Type: application/json

{
  "brIndeksa": "19001",
  "lIme": "Nenad",
  "imeRoditelja": "Ilija",
  "prezime": "Ivanovic",
  "smer": "Racunarstvo"
}
