@WebAPI_HostAddress = https://localhost:5276


GET {{WebAPI_HostAddress}}/Student/Preuzmi/Sve

###

GET {{WebAPI_HostAddress}}/Student/Preuzmi/Sortirani?brIndeksa=1802&ime=M

###

POST {{WebAPI_HostAddress}}/Student/Dodaj
Content-Type: application/json

{
  "brIndeksa": "19001",
  "lIme": "Marko",
  "imeRoditelja": "Ilija",
  "prezime": "Ivanovic",
  "smer": "Racunarstvo"
}

###

DELETE {{WebAPI_HostAddress}}/Student/Obrisi/19001

###

PUT {{WebAPI_HostAddress}}/Student/Izmeni
Content-Type: application/json

{
  "brIndeksa": "19001",
  "lIme": "Nenad",
  "imeRoditelja": "Ilija",
  "prezime": "Ivanovic",
  "smer": "Racunarstvo"
}

###

GET {{WebAPI_HostAddress}}/student/Preuzmi/19001

###

GET {{WebAPI_HostAddress}}/Student/VratiProjekte/18017

###
