@WebAPI_HostAddress = https://localhost:5276

# metoda za testiranje funkcionalnosti
GET {{WebAPI_HostAddress}}/Projekat/Teorijski/Preuzmi/ZaPredmet/CS102

###

POST {{WebAPI_HostAddress}}/Projekat/Teorijski/Dodaj
Content-Type: application/json

{
    "TipProjekta": "grupni",
    "Naziv": "Dizajn baze podataka za biblioteku",
    "SkolskaGodinaZadavanja": "2023/2024",
    "PripadaPredmetu": {
      "Id": "CS102"
    },
    "MaksBrojStrana": 70
}

###

# s obzirom da se dinamicki postavlja id projekta, postaviti odgovarajuci id za azuriranje
PUT {{WebAPI_HostAddress}}/Projekat/Teorijski/Izmeni
Content-Type: application/json

{
    "Id": 249,
    "TipProjekta": "grupni",
    "Naziv": "Dizajn baze podataka za biblioteku",
    "SkolskaGodinaZadavanja": "2023/2024",
    "PripadaPredmetu": {
      "Id": "CS102"
    },
    "MaksBrojStrana": 50
}

###

# s obzirom da se dinamicki postavlja id projekta, postaviti odgovarajuci id za brisanje
DELETE {{WebAPI_HostAddress}}/Projekat/Teorijski/Obrisi/249

###

# ovo ucesce i ucesce ispod se dodaju radi testiranja funkcionalnosti brisanja svih ucesca sa projekta
POST {{WebAPI_HostAddress}}/Ucesce/Dodaj/20/18033
Content-Type: application/json

{
  "DatumPocetkaIzrade": "2022-10-01T00:00:00",
  "RokZaZavrsetak": "2022-12-20T00:00:00",
  "DopunskaLiteratura": "C# in Depth by Jon Skeet"
}

###


POST {{WebAPI_HostAddress}}/Ucesce/Dodaj/20/18032
Content-Type: application/json

{
  "DatumPocetkaIzrade": "2022-10-01T00:00:00",
  "RokZaZavrsetak": "2022-12-20T00:00:00",
  "DopunskaLiteratura": "C# in Depth by Jon Skeet"
}

###

GET {{WebAPI_HostAddress}}/Projekat/Teorijski/Preuzmi/Studenti/20

###

DELETE {{WebAPI_HostAddress}}/Projekat/Teorijski/ObrisiSvaUcesca/20

###
  
GET {{WebAPI_HostAddress}}/Projekat/Teorijski/Preuzmi/15

###