@WebAPI_HostAddress = https://localhost:5276

GET {{WebAPI_HostAddress}}/Projekat/Teorijski/Literatura/Clanak/Preuzmi/Sve/5

###

POST {{WebAPI_HostAddress}}/Projekat/Teorijski/Literatura/Clanak/Dodaj/5
Content-Type: application/json

{
    "clanak": {
        "Naziv": "Clanak1",
        "ISSN": "1234-5678",
        "ImeCasopisa": "Casopis",
        "Broj": 10,
        "Godina": 2022
    },
    "autori": [
        {
            "Autor": "Jovan Dragojevic"
        },
        {
            "Autor": "Milutin Bojic"
        }
    ]
}

###s obzirom da se dinamicki postavlja id literature, postaviti odgovarajuci id za preuzimanje
GET {{WebAPI_HostAddress}}/Projekat/Teorijski/Literatura/Autori/Preuzmi/205

###s obzirom da se dinamicki postavlja id literature, postaviti odgovarajuci id za azuriranje

PUT {{WebAPI_HostAddress}}/Projekat/Teorijski/Literatura/Clanak/Izmeni
Content-Type: application/json

{
  "clanak": {
    "Id": 205,
    "Naziv": "Clanak1",
    "ISSN": "1234-5678",
    "ImeCasopisa": "Casopis",
    "Broj": 11,
    "Godina": 2023
  },
  "autori": [
    {
      "Autor": "Jovan Dragojevic"
    },
    {
      "Autor": "Milutin Bojic"
    }
  ]
}


###

DELETE {{WebAPI_HostAddress}}/Projekat/Teorijski/Literatura/Clanak/Obrisi/5/1234-5678

###

GET {{WebAPI_HostAddress}}/Projekat/Teorijski/Literatura/Clanak/Preuzmi/Id/1234-5678

###s obzirom da se dinamicki postavlja id literature, postaviti odgovarajuci id za brisanje

DELETE {{WebAPI_HostAddress}}/Projekat/Teorijski/Literatura/Obrisi/205
